# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ValentinesDay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ValentinesDay
  pod 'Mapbox-iOS-SDK', '~> 6.3.0'
  pod 'SideMenuSwift'
  pod 'Firebase/Firestore'
  pod 'SwiftMessages'

  target 'ValentinesDayTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ValentinesDayUITests' do
    # Pods for testing
  end

end
